### PR TITLE
Add a reset value button next to the SeekBar title

### PR DESCRIPTION
**Pull request by B1ays**
I found such a function useful enough to realize it.

### CODE REVIEW

**Comment by Mahmud0808** [comment]
I think it would be better if there was a small reset icon shown beside title (when value is changed). Otherwise no one will ever know that long pressing title will reset the value.

**Comment by B1ays** [comment]
OK, I'll rework it

**Comment by B1ays** [comment]
Screenshot_20230209-155854
Reset button Adobe Illustrator file:
[Reset button.zip](https://github.com/Mahmud0808/Iconify/files/10697361/Reset.button.zip)

**Comment by B1ays** [comment]
Done

**Pull request merged**
