### PR TITLE
Add KernelSU Support

### PR DESCRIPTION
**Pull request by mohamedamrnady**
I'm not really familiar with Java, but the pull request removed the magisk check in welcome page, adds KSU check, sets MODULE_DIR based on the KSU check, it should work fine (if KSU is fully functioning like magisk )

Tested on my phone (Android 13 with KSU with no other modules):

Before reboot:
- "Iconify" folder appear in the desired direction `/data/adb/ksu/modules`
- "Iconify" appear in the modules section in KSU app
- App (Iconify) shows reboot icon

After reboot:

- No folders found in `/data/adb/ksu/modules`
- No modules found in KSU app
- App re-shows welcome page with continue button which proceeds to re-install

### CODE REVIEW

**Comment by mohamedamrnady** [comment]
Tried installing another random module and its working
Retried installing Iconify but stuck at bootlogo (the one before the ROM's one)
Forced to delete `/data/adb/ksu/modules.img` to boot

**Comment by Mahmud0808** [comment]
So it's not working yet? Lemme know when you are able to make it work.

**Comment by mohamedamrnady** [comment]
I guess if we can have a flashable zip to flash in manager would work as kernelsu use a workaround so product/overlay files be placed

**Comment by Mahmud0808** [comment]
> I guess if we can have a flashable zip to flash in manager would work as kernelsu use a workaround so product/overlay files be placed

Did you check if that will work? Make a zip file of /data/adb/modules/Iconify folder. Then try flashing that.

**Comment by mohamedamrnady** [comment]
It worked. created zip and deleted the folder and flashed the zip and it booted and the app is running, finally, didn't thought about that before

if you want to merge the pr I could fix the conflicts in couple of days maximum

**Comment by Mahmud0808** [comment]
Sure, make a pull request, I will check. But probably I'll need time to merge it as I will also have to include a way to generate a module zip.

**Comment by mohamedamrnady** [comment]
rebased, just add code instead of ksu one in ModuleInstaller

**Comment by Mahmud0808** [comment]
Can you update me with the current status? I mean what extra do I have to implement to make it work? As I don't have kernel su yet, so I can't even test it.

**Comment by mohamedamrnady** [comment]
instead of copying files to MODULE_DIR, create a zip file (placed anywhere a normal user can access) and manually flashing it in KSU manager, or create a zip file in temp location and redirect to flash it in manager automatically

that would be placed after line 110 in moduleinstaller

the process is the same as the old one, so the user should manually create a zip file and flash it

I'm here to test at anytime

**Comment by Mahmud0808** [comment]
Can you also kindly contact in KernelSU telegram group? I don't actually have interest to make a separate flashable zip for some reason.

**Comment by mohamedamrnady** [comment]
I guess there is a much easier solution, instead of copying overlays to `/data/adb/modules/Iconify/system/product/overlay`, the files should be copied to `/data/adb/modules/Iconify/product/overlay` and create a symbolic link in `/data/adb/modules/Iconify/system` for `/system/product`

that worked for me instead of creating a zip file and flashing it

**Comment by Mahmud0808** [comment]
> I guess there is a much easier solution, instead of copying overlays to `/data/adb/modules/Iconify/system/product/overlay`, the files should be copied to `/data/adb/modules/Iconify/product/overlay` and create a symbolic link in `/data/adb/modules/Iconify/system` for `/system/product`

Can you kindly do the necessary changes for that in your pull request?

Edit: Tried what you said, put all overlays in `/data/adb/modules/Iconify/product/overlay` and created a symlink of `/system/product` in `/data/adb/modules/Iconify/system`. But after reboot the overlays are only inside module dir, they are not available anywhere else in the root directory.

**Comment by mohamedamrnady** [comment]
> Edit: Tried what you said, put all overlays in `/data/adb/modules/Iconify/product/overlay` and created a symlink of `/system/product` in `/data/adb/modules/Iconify/system`. But after reboot the overlays are only inside module dir, they are not available anywhere else in the root directory.

what ksu & manager version are you using ?

**Comment by H1mJT** [comment]
> instead of copying files to MODULE_DIR, create a zip file (placed anywhere a normal user can access) and manually flashing it in KSU manager, or create a zip file in temp location and redirect to flash it in manager automatically
> 
> that would be placed after line 110 in moduleinstaller
> 
> the process is the same as the old one, so the user should manually create a zip file and flash it
> 
> I'm here to test at anytime

Won't it be possible to use the cli module installtion method `/data/adb/ksud module install  /path/to/module.zip` to install the zip from Iconify itself .

**Comment by Mahmud0808** [comment]
> > Edit: Tried what you said, put all overlays in `/data/adb/modules/Iconify/product/overlay` and created a symlink of `/system/product` in `/data/adb/modules/Iconify/system`. But after reboot the overlays are only inside module dir, they are not available anywhere else in the root directory.
> 
> what ksu & manager version are you using ?

I tried with magisk. As I have to make sure it works on both Magisk and KSU.

**Comment by mohamedamrnady** [comment]
> I tried with magisk. As I have to make sure it works on both Magisk and KSU.

that's why I made separate installation processes

**Comment by Mahmud0808** [comment]
#102 looks simpler implementation so that has been merged. Thank you for telling which methods work on KSU. I will add your name in contributor list too.

**Pull request closed without merging**
