### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
as discussed in #32 here comes the Fastlane Starter Package. Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this (e.g. adding per-release changelogs), to adjust the description to your liking (HTML is fine as you can see – so some "evil stuff" like Javascript will be removed when sanitizing the content :wink:), replace screenshots…

If there are any questions, ask :smiley:

### CODE REVIEW

**Review by Mahmud0808 — APPROVED** [review]
Thank you. Apperciate it.

**Comment by IzzySoft** [comment]
Cool, I see you already built on it. Updated the config on my end and manually triggered an update, looks great, thanks! You'll see that reflected with the next sync tomorrow around 7 pm UTC then (instead of with the next release). Future changes will then be pulled along with new releases. Enjoy – I do!

PS: The changelog will probably not look as expected, as it's considered to be plain text (only `\n` gets replaced by `<br>`) – hence no nested lists. If you insist on those, you can try non-breakable spaces, but better not try HTML there. Not sure how fdroidserver would handle that.

**Comment by Mahmud0808** [comment]
Thanks for the tip. I will check on it later.

**Comment by IzzySoft** [comment]
With the next release will suffice I guess. Btw, it's only the latest changelog shown anyway (at least currently) – i.e. the one matching the latest release listed in the index on the user's device.

**Comment by Mahmud0808** [comment]
> With the next release will suffice I guess. Btw, it's only the latest changelog shown anyway (at least currently) – i.e. the one matching the latest release listed in the index on the user's device.

Do I need a gitlab account to publish app on Fdroid? I don't wanna maintain 2 repository at a time. xd

**Comment by IzzySoft** [comment]
No need to maintain a GitLab repo for your app – every forge working with git (e.g. Codeberg, Sourcehut, GitLab, Github) is supported by F-Droid. But to communicate with the F-Droid team, an *account* there would help, yes. Else it would be an extra burden to carry questions and answers around between issues/MRs there and your issue tracker here, and also make following them more difficult.

**Comment by Mahmud0808** [comment]
Updated branch name. Hope this won't be a serious issue.

**Comment by IzzySoft** [comment]
Only for my Fastlane updater – so thanks for telling me! Shall I then pull Fastlane from `beta` or from `stable` (ideally the name stays then for a while)?

Btw, in case I forgot to tell you: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to your app in my repo e.g. from your Readme :smiley:

**Comment by Mahmud0808** [comment]
> Only for my Fastlane updater – so thanks for telling me! Shall I then pull Fastlane from `beta` or from `stable` (ideally the name stays then for a while)?
> 
> Btw, in case I forgot to tell you: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to your app in my repo e.g. from your Readme 😃

Pull from stable. Cause I will be regularly changing beta for testing purposes and I don't want that to be pulled.

**Comment by IzzySoft** [comment]
Thanks! Config updated. And thanks for adding the badge :star_struck:

**Pull request merged**
