### PR TITLE
WeatherConfig: Add 15 and 30 minutes interval

### PR DESCRIPTION
**Pull request by 0xsharkboy**
It allows users like me to be able to set a smaller interval. I am changing city a lot during my work days, I found that 1h was not enought. I changed the interval unit to minutes in scheduler to do so

### CODE REVIEW

**Comment by DHD2280** [comment]
We have decided to use a large update interval, like 1h, to avoid too many calls for free weather APIs.
OpenMeteo offers a free API, imagine if every user would use 15 minutes with a free API key.

**Comment by 0xsharkboy** [comment]
Yeah I understand, no problem ! I'll just use my fork then

Thanks for your great job on this app

**Comment by DHD2280** [comment]
> Yeah I understand, no problem ! I'll just use my fork then
> 
> Thanks for your great job on this app

You can also register to OpenWeatherMap and use your own key, they also offer a free key, so you will not overcome OpenMeteo API call limits.

**Comment by 0xsharkboy** [comment]
Yeah sure, that's already what I'm using

**Pull request closed without merging**
